$(function(){
   $(".dian2").mouseover(function(){
        $(".p2").stop().slideDown(500);
   });
    $(".dian2").mouseout(function(){
        $(".p2").stop().slideUp(500);
    });
    $(".dian3").mouseover(function(){
        $(".p3").stop().slideDown(500);
    });
    $(".dian3").mouseout(function(){
        $(".p3").stop().slideUp(500);
    });
    $(".dian4").mouseover(function(){
        $(".p4").stop().slideDown(500);
    });
    $(".dian4").mouseout(function(){
        $(".p4").stop().slideUp(500);
    });
    $(".dian5").mouseover(function(){
        $(".p5").stop().slideDown(500);
    });
    $(".dian5").mouseout(function(){
        $(".p5").stop().slideUp(500);
    })
});